server:
  ssl:
    key-store: "classpath:keystore/springboot.p12"
    key-store-password: "password"
    key-store-type: "pkcs12"
    key-alias: "springboot"
    key-password: "password"
    enabled: true
  port: 8443
  servlet:
    context-path: "/api"
spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: ""
            clientSecret: ""
            scope:
              - openid
              - address
              - profile
              - phone
              - email
          github:
            clientId: ""
            clientSecret: ""
            scope:
              - user:email
              - read:user
          facebook:
            clientId: ""
            clientSecret: ""
            scope:
              - public_profile
